<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>PhotonLab.Desktop</AssemblyName>
        <RootNamespace>PhotonLab.Desktop</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PhotonLab.Core\PhotonLab.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\Native\PhotonLab.Native\build\PhotonLab.NativeDLL.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BitMiracle.LibTiff.NET" Version="2.4.649" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />

        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.9" />
    </ItemGroup>

</Project>